#ifndef DEPEN
#define DEPEN
#include "Ship.h"
#include <iostream>
#include "SmallShip.h"
#include "EnemyManager.h"
#include "Bullet.h"
#include "Keyboard.h"
#include "Explosion.h"
using std::vector;
#endif DEPEN