#ifndef DEPEN
#define DEPEN
#include "Ship.h"
#include <iostream>
#include "SmallShip.h"
#include "Manager.h"
#include "Bullet.h"
#include "Keyboard.h"
#include "Explosion.h"
#include "ScoreBoard.h"
#include "Core.h"
using Core::Graphics;
using std::vector;
#endif DEPEN